### ISSUE TITLE
`checknonsingular(::Int64, ::Val{true})` removed in Julia 1.7

### ISSUE THREAD

**Issue by KristofferC** [JuliaMatrices/MatrixFactorizations.jl#26]
Causes test error at https://github.com/JuliaMatrices/MatrixFactorizations.jl/blob/22208192872a12a556e2d1fc5c52725642a15cb9/src/ul.jl#L181

**Comment by dlfivefifty** [comment]
Thanks. I usually wait for release candidates to update packages but I guess 1.7 is already in beta?

**Comment by dlfivefifty** [comment]
Here's the relevant commit: https://github.com/JuliaLang/julia/commit/e0ecc557a24eb3338b8dc672d02c98e8b31111fa#diff-8d1e6cd3179ba632a02c2d34dbd7a98dad914325c262d7d7e2ddb84a3a6496af

Very nice change I have to say

**Comment by KristofferC** [comment]
You can already enable 1.7 in CI.

**Comment by dlfivefifty** [comment]
Fixed.
